GET http://localhost:4000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTY0OTcwMzIzMn0.em3EoUp65JPoeJ66llOEkwrmFbE_1_1OMb0jM37x5Qg



###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Jill"
}